server:
  port: 16731
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/kaotu?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    port: 16729
    password: 123456
kaotu:
  jwt:
    secret-key: itkaotu
    ttl: 172800000 # 2 days in milliseconds
  log:
    directory: logs
  recommend:
    url: http://10.242.1.62:5000/recommend
logging:
  config: classpath:logback.xml
