server:
  port: 16733
spring:
  application:
    name: admin-service
  datasource:
#    url: jdbc:mysql://localhost:3306/kaotu?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:16728/kaotu?useSSL=false&serverTimezone=UTC
    username: root
#    password: 123456
    password: mysql
kaotu:
  jwt:
    secret-key: itkaotu-admin
    ttl: 3600000 # 1 hour